AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-sam

  AWS Secret SAM Template for test-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 4
    MemorySize: 128

Resources:
  AWSSecretFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: secrets_api/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role: arn:aws:iam::068155203304:role/Secrets_manager_lambda
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /secret/{secret_name}
            Method: get
      Layers:
        - arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AWSSecretApi:
    Description: "API Gateway endpoint URL for Prod stage for AWS Secret function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AWSSecretFunction:
    Description: "AWS Secret Lambda Function ARN"
    Value: !GetAtt AWSSecretFunction.Arn
  AWSSecretFunctionIamRole:
    Description: "Implicit IAM Role created for AWS Secret function"
    Value: !GetAtt AWSSecretFunctionRole.Arn
